# ============================================
# 评测配置：
#   - 数据集hf路径
#   - 数据集split
#   - 数据集size
#   - 数据集模态
#   - 评测方式（multiple choice / generation / ...）
#   - 评测指标（accuracy / ...）
#   - 是否支持few_shot
#   - 选项编号形式（ABCD或1234...），判断对错时的标识(true/false或者1/0...)
# ============================================
dataset:
  name: gsm8k
  path: openai/gsm8k
  split: test
  size: 
  modality: text-to-text
  fewshot_data_path: openai/gsm8k
  fewshot_data_file: null
  fewshot_data_split: train
  cot_fewshot_data_path: benchmarks/cot_fewshot
  cot_fewshot_data_file: gsm8k_main.json
  cot_fewshot_data_split: train
  max_shot: 5
  default_task_list: ["main"]
task: 
  - name: main
    type: Dialogue
    data_files: ["main/test*.parquet"]  # Optional, if not specified, dataset will be loaded through the task name
    question_key: question
    answer_key: null
    ground_truth_key: answer
    candidate_labels: null
    avalable_evaluate_tools: ["match_number_after_pattern", "match_number_after_answer", "match_last_number", "match_first_number"] # first one as default
  - name: multi_choice  # example
    type: MultiChoice
    data_files: null
    question_key: question
    answer_key: choice
    ground_truth_key: answer
    candidate_labels: [A, B, C, D]
    avalable_evaluate_tools: ["match_number_after_pattern", "match_number_after_answer", "match_last_number", "match_first_number"]
answer_extractor:
  - name: match_number_after_pattern
    function: regex_match_number
    args:
      additional_pattern: "#### {original_pattern}"
      match_index: -1   # Take the last match
  - name: match_number_after_answer
    function: regex_match_number
    args:
      additional_pattern: "The answer is {original_pattern}."
      match_index: -1
  - name: match_last_number
    function: regex_match_number
    args:
      match_index: -1
  - name: match_first_number
    function: regex_match_number
    args:
      match_index: 0   # Take the first match
metrics:
  - name: accuracy
    function: accuracy
    args:
overall_metrics:
  - name: null
    function: null
    args:
      null
  