  # Evaluation configurations
  eval_cfgs:
    # Output directory
    output_dir: ../output
    # Cache directory, if not specified, cache will not be saved
    cache_dir: ../cache
    # Unique identifier for current task
    task_uid: 111
    # benchmark name and task name, if the task list is empty, all tasks will be evaluated
    benchmarks: {
      "gsm8k": ["main"],
      "mmlu": ["global_facts"],
      "HumanEval": ["openai_humaneval"],
      "AGIEval": ['aqua-rat', 'gaokao-biology', 'gaokao-chemistry', 'gaokao-chinese', 'gaokao-english', 'gaokao-geography', 'gaokao-history', 'gaokao-mathcloze', 'gaokao-mathqa', 'gaokao-physics', 'jec-qa-ca', 'jec-qa-kd', 'logiqa-en', 'logiqa-zh', 'lsat-ar', 'lsat-lr', 'lsat-rc', 'math', 'sat-en', 'sat-en-without-passage', 'sat-math'],
      "TruthfulQA": ["generation"],
      "mmmu": ["Accounting"],
      }
    # Num shot
    n_shot: {
      "gsm8k": 5,
      "mmlu": 0,
      "HumanEval": 0,
      "AGIEval": 5,
      "TruthfulQA": 6,
      "mmmu": 5,
      }
    # Chain of thought
    cot: {
      "gsm8k": True,
      "mmlu": True,
      "HumanEval": False,
      "AGIEval": False,
      "TruthfulQA": False,
      "mmmu": False,
      }
  # The model configurations
  model_cfgs:
    # Pretrained model unique identity
    model_id: Llama3.1-8B-Instruct
    # Pretrained model name or path
    model_name_or_path: meta-llama/Llama-3.1-8B-Instruct
    # Model type ("LM" or "MM")
    model_type: "LM"
    # Chat template
    chat_template: Llama3
  infer_cfgs:
    # Inference backend
    infer_backend: "vllm"
    # Whether to trust remote code
    trust_remote_code: True
    # The max token length
    model_max_length: 2048
    # The max new tokens
    max_new_tokens: 512
    # The number of Output
    num_output: 1
    # Top-K
    top_k: 50
    # Top-P
    top_p: 0.95
    # Temperature
    temperature: 0.1
    # Prompt Logprobs
    prompt_logprobs: 0
    # Logprobs
    logprobs: 20
    # Beam Search
    beam_search: False
    # Beam Search size
    num_beams: null
    # Number of GPUs
    num_gpu: 2
    # Available GPU IDs. If not specified, first num_gpu GPUs will be used.
    gpu_ids: [0,1]
    # GPU utilization
    gpu_utilization: 0.8
    